baseURL = ""
languageCode = "en-us"
title = "Air-Sea Modeling laboratory"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Air-Sea Modeling laboratory"
    description = "Department of Atmospheric Sciences, Yonsei University"
    email = "hajsong@yonsei.ac.kr"
    phone = "+82 2 2123 2579"
    address = "Science Hall #544, 50 Yonsei-ro Seodaemun-gu, Seoul, Korea"
    year = 2018
    background = "hi"
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showGroup = true
    showRecentWorks = true
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = false
    footerEnableTextWidget = true
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3
[[menu.main]]
    name = "Group"
    url = "/group/"
    weight = 2
[[menu.main]]
    name = "Publication"
    url = "/publication/"
    weight = 4
[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/nickname"
    icon = "fa-facebook-square"
    footer = false
    sharethis = true
    network = "facebook"
[[params.social]]
    title = "twitter"
    url = "https://twitter.com/nickname"
    icon = "fa-twitter-square"
    footer = false
    sharethis = true
    network = "twitter"
[[params.social]]
    title = "instagram"
    url = "https://www.instagram.com/nickname"
    icon = "fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
    title = "google+"
    url = "https://plus.google.com/+nickname"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
    title = "tumblr"
    url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
    title = "github"
    url = "https://github.com/nickname"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
    title = "email"
    url = "mailto:hajsong@yonsei.ac.kr"
    icon = "fa-envelope"
    footer = true
    sharethis = true
    network = "email"
